package com.leafcabral.pontoDeVenda.views;

import com.leafcabral.pontoDeVenda.dao.DatabaseDAO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

public class LoginDialog extends javax.swing.JDialog {
	private boolean loginSuccessful = false;

	/**
	 * Creates new form LoginDialog
	 */
	public LoginDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);
		
		getRootPane().setDefaultButton(btnConectar);
		KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0);
		javax.swing.Action escapeAction = new javax.swing.AbstractAction() {
			public void actionPerformed(java.awt.event.ActionEvent e) {
				dispose(); 
			}
		}; 
		getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
		getRootPane().getActionMap().put("ESCAPE", escapeAction);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnCancelar = new javax.swing.JButton();
                btnConectar = new javax.swing.JButton();
                hostPanel = new javax.swing.JPanel();
                hostLabel = new javax.swing.JLabel();
                hostTextField = new javax.swing.JTextField();
                userPanel = new javax.swing.JPanel();
                userLabel = new javax.swing.JLabel();
                userTextField = new javax.swing.JTextField();
                passwrdPanel = new javax.swing.JPanel();
                passwrdLabel = new javax.swing.JLabel();
                passwrdTextField = new javax.swing.JPasswordField();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Configuração do Banco de Dados");
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowOpened(java.awt.event.WindowEvent evt) {
                                formWindowOpened(evt);
                        }
                });

                btnCancelar.setForeground(new java.awt.Color(255, 102, 102));
                btnCancelar.setText("Cancelar");
                btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelarActionPerformed(evt);
                        }
                });

                btnConectar.setText("Conectar");
                btnConectar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnConectarActionPerformed(evt);
                        }
                });

                hostLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                hostLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                hostLabel.setText("Host/URL:");
                hostLabel.setToolTipText("");

                hostTextField.setText("jdbc:mysql://localhost:3306/exemplopdv");

                javax.swing.GroupLayout hostPanelLayout = new javax.swing.GroupLayout(hostPanel);
                hostPanel.setLayout(hostPanelLayout);
                hostPanelLayout.setHorizontalGroup(
                        hostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hostPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
                );
                hostPanelLayout.setVerticalGroup(
                        hostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hostPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(hostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(hostLabel)
                                        .addComponent(hostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                userLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                userLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                userLabel.setText("Usuário:");
                userLabel.setToolTipText("");

                userTextField.setText("root");
                userTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                userTextFieldActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
                userPanel.setLayout(userPanelLayout);
                userPanelLayout.setHorizontalGroup(
                        userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
                );
                userPanelLayout.setVerticalGroup(
                        userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userLabel)
                                        .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                passwrdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                passwrdLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                passwrdLabel.setText("Senha:");
                passwrdLabel.setToolTipText("");

                javax.swing.GroupLayout passwrdPanelLayout = new javax.swing.GroupLayout(passwrdPanel);
                passwrdPanel.setLayout(passwrdPanelLayout);
                passwrdPanelLayout.setHorizontalGroup(
                        passwrdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(passwrdPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(passwrdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(passwrdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                passwrdPanelLayout.setVerticalGroup(
                        passwrdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(passwrdPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(passwrdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwrdLabel)
                                        .addComponent(passwrdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwrdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 10, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConectar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)
                                .addGap(37, 37, 37))
                );

                layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hostPanel, passwrdPanel, userPanel});

                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(hostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passwrdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancelar)
                                        .addComponent(btnConectar))
                                .addContainerGap(18, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
				// TODO add your handling code here:
        }//GEN-LAST:event_userTextFieldActionPerformed

        private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
		String host = hostTextField.getText().trim();
		String usuario = userTextField.getText().trim();
		String senha = new String(passwrdTextField.getPassword());
		
		if (host.isEmpty() || usuario.isEmpty()) {
			JOptionPane.showMessageDialog(this, 
				"Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
			return;
		}
		
		// Set database credentials
		DatabaseDAO.setDatabaseCredentials(host, usuario, senha);
		
		// Test connection
		if (DatabaseDAO.testConnection()) {
			loginSuccessful = true;
			JOptionPane.showMessageDialog(this, 
				"Conexão estabelecida com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
			dispose();
		} else {
			JOptionPane.showMessageDialog(this, 
				"Falha na conexão! Verifique as credenciais.", "Erro", JOptionPane.ERROR_MESSAGE);
		}
        }//GEN-LAST:event_btnConectarActionPerformed

        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
                System.exit(0);
        }//GEN-LAST:event_btnCancelarActionPerformed

        private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
		// Foi não :(
        }//GEN-LAST:event_formWindowOpened

	public boolean isLoginSuccessful() {
		return loginSuccessful;
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancelar;
        private javax.swing.JButton btnConectar;
        private javax.swing.JLabel hostLabel;
        private javax.swing.JPanel hostPanel;
        private javax.swing.JTextField hostTextField;
        private javax.swing.JLabel passwrdLabel;
        private javax.swing.JPanel passwrdPanel;
        private javax.swing.JPasswordField passwrdTextField;
        private javax.swing.JLabel userLabel;
        private javax.swing.JPanel userPanel;
        private javax.swing.JTextField userTextField;
        // End of variables declaration//GEN-END:variables
}
