/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.leafcabral.pontoDeVenda.views;

import com.leafcabral.pontoDeVenda.dao.ProdutoDAO;
import com.leafcabral.pontoDeVenda.models.Produto;
import java.awt.Image;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ftfer
 */
public class TelaProdutos extends javax.swing.JFrame {
	
	Produto objAlterar = null;
	
	/**
	 * Creates new form TelaProdutos
	 */
	public TelaProdutos(int tab) {
		initComponents();
		this.setLocationRelativeTo(null);
		this.pnlGuiasProduto.setSelectedIndex(tab);
		
		try {
			Image i = ImageIO.read(getClass().getResource("/APP-ICON.png"));
			this.setIconImage(i);
		} catch (Exception e) { }
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pnlGuiasProduto = new javax.swing.JTabbedPane();
                pnlCadastroProduto = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                lblIDProduto = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                txtCodigoProdutoCadastro = new javax.swing.JTextField();
                txtNomeProdutoCadastro = new javax.swing.JTextField();
                txtValorProdutoCadastro = new javax.swing.JTextField();
                txtQtdProdutoCadastro = new javax.swing.JTextField();
                btnConfirmarCadastroProduto = new javax.swing.JButton();
                btnCancelarCadastroProduto = new javax.swing.JButton();
                pnlConsultaProduto = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                nomeTextField = new javax.swing.JTextField();
                btnPesquisarProduto = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblProdutos = new javax.swing.JTable();
                btnAlterar = new javax.swing.JButton();
                btnExcluir = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Editar/Ver Produtos");

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel1.setText("ID:");
                jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel2.setText("Nome:");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel3.setText("Valor:");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel4.setText("Qtd:");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel6.setText("Código:");

                btnConfirmarCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-icon.png"))); // NOI18N
                btnConfirmarCadastroProduto.setText("Confirmar");
                btnConfirmarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnConfirmarCadastroProdutoActionPerformed(evt);
                        }
                });

                btnCancelarCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross-icon.png"))); // NOI18N
                btnCancelarCadastroProduto.setText("Cancelar");

                javax.swing.GroupLayout pnlCadastroProdutoLayout = new javax.swing.GroupLayout(pnlCadastroProduto);
                pnlCadastroProduto.setLayout(pnlCadastroProdutoLayout);
                pnlCadastroProdutoLayout.setHorizontalGroup(
                        pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtQtdProdutoCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(txtValorProdutoCadastro, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCodigoProdutoCadastro)
                                        .addComponent(txtNomeProdutoCadastro)
                                        .addComponent(lblIDProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnConfirmarCadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(btnCancelarCadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(22, Short.MAX_VALUE))
                );

                pnlCadastroProdutoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel6});

                pnlCadastroProdutoLayout.setVerticalGroup(
                        pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addComponent(lblIDProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCodigoProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtNomeProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtValorProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnConfirmarCadastroProduto))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtQtdProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelarCadastroProduto))
                                .addContainerGap(42, Short.MAX_VALUE))
                );

                pnlCadastroProdutoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelarCadastroProduto, txtQtdProdutoCadastro});

                pnlCadastroProdutoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConfirmarCadastroProduto, txtValorProdutoCadastro});

                pnlGuiasProduto.addTab("Cadastrar", pnlCadastroProduto);

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel5.setText("Nome:");

                nomeTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                nomeTextField.setPreferredSize(new java.awt.Dimension(64, 22));

                btnPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-icon.png"))); // NOI18N
                btnPesquisarProduto.setText("Pesquisar");
                btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPesquisarProdutoActionPerformed(evt);
                        }
                });

                tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "ID", "Codigo", "Nome", "Valor", "Quantidade"
                        }
                ));
                jScrollPane1.setViewportView(tblProdutos);

                btnAlterar.setText("Alterar");
                btnAlterar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAlterarActionPerformed(evt);
                        }
                });

                btnExcluir.setBackground(new java.awt.Color(255, 102, 102));
                btnExcluir.setText("Excluir");
                btnExcluir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExcluirActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout pnlConsultaProdutoLayout = new javax.swing.GroupLayout(pnlConsultaProduto);
                pnlConsultaProduto.setLayout(pnlConsultaProdutoLayout);
                pnlConsultaProdutoLayout.setHorizontalGroup(
                        pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaProdutoLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                pnlConsultaProdutoLayout.setVerticalGroup(
                        pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(nomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                                .addComponent(jLabel5))
                                        .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaProdutoLayout.createSequentialGroup()
                                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(15, Short.MAX_VALUE))
                );

                pnlConsultaProdutoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPesquisarProduto, nomeTextField});

                pnlGuiasProduto.addTab("Consultar", pnlConsultaProduto);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlGuiasProduto)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlGuiasProduto)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
		
		DefaultTableModel modeloProdutos = (DefaultTableModel) tblProdutos.getModel();
		
		int linhaSelecionada = tblProdutos.getSelectedRow();
		
		if(linhaSelecionada>=0){
			int idExcluir = Integer.parseInt(modeloProdutos.getValueAt(linhaSelecionada, 0).toString());
			
			boolean retorno = ProdutoDAO.excluir(idExcluir);
			if(retorno ){
				JOptionPane.showMessageDialog(rootPane,
						"Produto excluído com sucesso!");
				atualizarTabela();
			}else{
				JOptionPane.showMessageDialog(rootPane,
						"Falha ao excluir o produto!");
			}
		}
		
    }//GEN-LAST:event_btnExcluirActionPerformed

	public void atualizarTabela(){
		ArrayList<Produto> listaRetorno = ProdutoDAO.listar();
		
		DefaultTableModel modeloProdutos = (DefaultTableModel) tblProdutos.getModel();
		
		modeloProdutos.setRowCount(0);
		
		for (Produto item : listaRetorno) {
			
			modeloProdutos.addRow(new String[]{
				String.valueOf(item.getIdProduto()),
				String.valueOf(item.getCodProduto()),
				item.getNomeProduto(),
				String.valueOf(item.getValorProduto()),
				String.valueOf(item.getQtdProduto())
			});		   
		}
	}
	
    private void btnConfirmarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCadastroProdutoActionPerformed

				
		if(objAlterar !=null){
		
			
			int codProduto = Integer.parseInt(txtCodigoProdutoCadastro.getText());
			String nomeProduto = txtNomeProdutoCadastro.getText();
			int qtdProduto = Integer.parseInt(txtQtdProdutoCadastro.getText());
			float valorProduto = Float.parseFloat(txtValorProdutoCadastro.getText());
			
			int idProduto = Integer.parseInt(lblIDProduto.getText());
			
			objAlterar.setIdProduto(idProduto);
			objAlterar.setNomeProduto(nomeProduto);
			objAlterar.setQtdProduto(qtdProduto);
			objAlterar.setValorProduto(valorProduto);
			objAlterar.setCodProduto(codProduto);
			
			boolean retorno = ProdutoDAO.alterar(objAlterar);

			if(retorno){
				JOptionPane.showMessageDialog(rootPane,
						"Sucesso na alteração!");

				txtCodigoProdutoCadastro.setText("");
				txtQtdProdutoCadastro.setText("");
				txtNomeProdutoCadastro.setText("");
				lblIDProduto.setText("");
				txtValorProdutoCadastro.setText("");

			}else{
				JOptionPane.showMessageDialog(rootPane,
						"Falha!");
			}
			
		}else{
			//Modo de inclusão
			int codProduto = Integer.parseInt(txtCodigoProdutoCadastro.getText());
			String nomeProduto = txtNomeProdutoCadastro.getText();
			int qtdProduto = Integer.parseInt(txtQtdProdutoCadastro.getText());
			float valorProduto = Float.parseFloat(txtValorProdutoCadastro.getText());

			Produto objNovo = new Produto(codProduto, nomeProduto, qtdProduto, valorProduto);

			//Chamar a DAO
			boolean retorno = ProdutoDAO.salvar(objNovo);

			if(retorno){
				JOptionPane.showMessageDialog(rootPane,
						"Sucesso!");

				txtCodigoProdutoCadastro.setText("");
				txtQtdProdutoCadastro.setText("");
				txtNomeProdutoCadastro.setText("");
				lblIDProduto.setText("");
				txtValorProdutoCadastro.setText("");

			}else{
				JOptionPane.showMessageDialog(rootPane,
						"Falha!");
			}
		}

		
		
		
    }//GEN-LAST:event_btnConfirmarCadastroProdutoActionPerformed

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
		String nomePesquisa = nomeTextField.getText().trim();
		
		ArrayList<Produto> listaRetorno;
		
		listaRetorno = ProdutoDAO.listar();
		if (nomePesquisa.isEmpty()) {
			listaRetorno = ProdutoDAO.listar();
		} else {
			listaRetorno = ProdutoDAO.buscarPorNomeParcial(nomePesquisa);
		}
		DefaultTableModel modeloProdutos = (DefaultTableModel) tblProdutos.getModel();
		
		modeloProdutos.setRowCount(0);
		
		for (Produto item : listaRetorno) {
			
			modeloProdutos.addRow(new String[]{
				String.valueOf(item.getIdProduto()),
				String.valueOf(item.getCodProduto()),
				item.getNomeProduto(),
				String.valueOf(item.getValorProduto()),
				String.valueOf(item.getQtdProduto())
			});		   
		}

		
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
		
		DefaultTableModel modeloProdutos = (DefaultTableModel) tblProdutos.getModel();
		
		int linhaSelecionada = tblProdutos.getSelectedRow();
		if(linhaSelecionada>=0){
			int id = Integer.parseInt(modeloProdutos.getValueAt(linhaSelecionada, 0).toString());
			int codProduto = Integer.parseInt(modeloProdutos.getValueAt(linhaSelecionada, 1).toString());
			String nomeProduto = modeloProdutos.getValueAt(linhaSelecionada, 2).toString();
			float valorProduto = Float.parseFloat(modeloProdutos.getValueAt(linhaSelecionada, 3).toString());
			int qtdProduto = Integer.parseInt(modeloProdutos.getValueAt(linhaSelecionada, 4).toString());
			
			objAlterar = new Produto(id,codProduto,nomeProduto,qtdProduto,valorProduto);
			
			//Volto pra aba de cadastro
			pnlGuiasProduto.setSelectedIndex(0);
			
			//Passo os dados do objeto para os campos
			lblIDProduto.setText(String.valueOf(objAlterar.getIdProduto()));
			txtCodigoProdutoCadastro.setText(String.valueOf(objAlterar.getCodProduto()));
			txtValorProdutoCadastro.setText(String.valueOf(objAlterar.getValorProduto()));
			txtQtdProdutoCadastro.setText(String.valueOf(objAlterar.getQtdProduto()));
			txtNomeProdutoCadastro.setText(objAlterar.getNomeProduto());
			
		}
		
    }//GEN-LAST:event_btnAlterarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaProdutos(0).setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAlterar;
        private javax.swing.JButton btnCancelarCadastroProduto;
        private javax.swing.JButton btnConfirmarCadastroProduto;
        private javax.swing.JButton btnExcluir;
        private javax.swing.JButton btnPesquisarProduto;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblIDProduto;
        private javax.swing.JTextField nomeTextField;
        private javax.swing.JPanel pnlCadastroProduto;
        private javax.swing.JPanel pnlConsultaProduto;
        private javax.swing.JTabbedPane pnlGuiasProduto;
        private javax.swing.JTable tblProdutos;
        private javax.swing.JTextField txtCodigoProdutoCadastro;
        private javax.swing.JTextField txtNomeProdutoCadastro;
        private javax.swing.JTextField txtQtdProdutoCadastro;
        private javax.swing.JTextField txtValorProdutoCadastro;
        // End of variables declaration//GEN-END:variables
}
