/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.leafcabral.pontoDeVenda.views;

import com.leafcabral.pontoDeVenda.dao.ClienteDAO;
import com.leafcabral.pontoDeVenda.models.Cliente;
import java.awt.Image;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ftfer
 */
public class TelaClientes extends javax.swing.JFrame {
	
	Cliente objAlterar = null;
	
	/**
	 * Creates new form TelaClientes
	 */
	public TelaClientes(int tab) {
		initComponents();
		this.setLocationRelativeTo(null);
		this.pnlGuiasCliente.setSelectedIndex(tab);
		
		try {
			Image i = ImageIO.read(getClass().getResource("/APP-ICON.png"));
			this.setIconImage(i);
		} catch (Exception e) { }
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pnlGuiasCliente = new javax.swing.JTabbedPane();
                pnlCadastroCliente = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                txtCPFCadastro = new javax.swing.JFormattedTextField();
                jLabel2 = new javax.swing.JLabel();
                lblIDCliente = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtNomeCadastro = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                txtEmailCadastro = new javax.swing.JTextField();
                btnConfirmarCadastroCliente = new javax.swing.JButton();
                btnCancelarCadastroCliente = new javax.swing.JButton();
                pnlConsultarCliente = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                txtNomeConsultar = new javax.swing.JTextField();
                btnPesquisarNomeCliente = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblClientes = new javax.swing.JTable();
                btnAlterarCliente = new javax.swing.JButton();
                btnExcluirCliente = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Editar/Ver Clientes");

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel1.setText("CPF:");

                try {
                        txtCPFCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel2.setText("ID:");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel3.setText("Nome:");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                jLabel4.setText("Email:");

                btnConfirmarCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-icon.png"))); // NOI18N
                btnConfirmarCadastroCliente.setText("Confirmar");
                btnConfirmarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnConfirmarCadastroClienteActionPerformed(evt);
                        }
                });

                btnCancelarCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross-icon.png"))); // NOI18N
                btnCancelarCadastroCliente.setText("Cancelar");

                javax.swing.GroupLayout pnlCadastroClienteLayout = new javax.swing.GroupLayout(pnlCadastroCliente);
                pnlCadastroCliente.setLayout(pnlCadastroClienteLayout);
                pnlCadastroClienteLayout.setHorizontalGroup(
                        pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCPFCadastro)
                                        .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                                                .addComponent(txtNomeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnConfirmarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                                                .addComponent(txtEmailCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnCancelarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(25, Short.MAX_VALUE))
                );

                pnlCadastroClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCPFCadastro, txtEmailCadastro, txtNomeCadastro});

                pnlCadastroClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

                pnlCadastroClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarCadastroCliente, btnConfirmarCadastroCliente});

                pnlCadastroClienteLayout.setVerticalGroup(
                        pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(lblIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCPFCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(btnConfirmarCadastroCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(btnCancelarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(131, Short.MAX_VALUE))
                );

                pnlCadastroClienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelarCadastroCliente, btnConfirmarCadastroCliente, txtCPFCadastro, txtEmailCadastro, txtNomeCadastro});

                pnlGuiasCliente.addTab("Cadastrar", pnlCadastroCliente);

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel5.setText("Nome:");

                txtNomeConsultar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtNomeConsultarActionPerformed(evt);
                        }
                });

                btnPesquisarNomeCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-icon.png"))); // NOI18N
                btnPesquisarNomeCliente.setText("Pesquisar");
                btnPesquisarNomeCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPesquisarNomeClienteActionPerformed(evt);
                        }
                });

                tblClientes.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "ID", "CPF", "Nome", "Email"
                        }
                ));
                jScrollPane1.setViewportView(tblClientes);

                btnAlterarCliente.setText("Alterar");
                btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAlterarClienteActionPerformed(evt);
                        }
                });

                btnExcluirCliente.setBackground(new java.awt.Color(255, 102, 102));
                btnExcluirCliente.setText("Excluir");
                btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnExcluirClienteActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout pnlConsultarClienteLayout = new javax.swing.GroupLayout(pnlConsultarCliente);
                pnlConsultarCliente.setLayout(pnlConsultarClienteLayout);
                pnlConsultarClienteLayout.setHorizontalGroup(
                        pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNomeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPesquisarNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnExcluirCliente))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pnlConsultarClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterarCliente, btnExcluirCliente});

                pnlConsultarClienteLayout.setVerticalGroup(
                        pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNomeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPesquisarNomeCliente))
                                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11)
                                                .addComponent(btnExcluirCliente)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pnlConsultarClienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPesquisarNomeCliente, txtNomeConsultar});

                pnlConsultarClienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterarCliente, btnExcluirCliente});

                pnlGuiasCliente.addTab("Consultar", pnlConsultarCliente);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlGuiasCliente)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlGuiasCliente)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCadastroClienteActionPerformed
		
		//Se tiver em alteração
		if(objAlterar!= null){
			//modo de alteração
			
			//Resgato os dados alterados
			String nome = txtNomeCadastro.getText();
			String email = txtEmailCadastro.getText();
			
			objAlterar.setNomeCliente(nome);
			objAlterar.setEmailCliente(email);
			
			//TODO: Chamar a DAO para alterar
			boolean retornoAlteracao = ClienteDAO.alterar(objAlterar);
			if(retornoAlteracao){
				JOptionPane.showMessageDialog(rootPane,
						"Sucesso ao alterar!");
				
				//Limpar campos da tela de cadastro
				objAlterar = null;
				txtNomeCadastro.setText("");
				txtEmailCadastro.setText("");
				txtCPFCadastro.setText("");
				lblIDCliente.setText("");
				
			}else{
				JOptionPane.showMessageDialog(rootPane,
						"Falha ao alterar");
			}
					
		
		}else{
			//Modo de inclusão
			//1) Passando os dados da interface para um objeto
			String cpf = txtCPFCadastro.getText();
			String nome = txtNomeCadastro.getText();
			String email = txtEmailCadastro.getText();

			Cliente objCadastrar = new Cliente(nome,email, cpf);

			//2) Passar o objeto para o banco de dados
			boolean retornoBanco = ClienteDAO.salvar(objCadastrar);

			if(retornoBanco){
				JOptionPane.showMessageDialog(rootPane,
						"Cliente cadastrado com sucesso!");
				
				lblIDCliente.setText("");
				txtNomeCadastro.setText("");
				txtCPFCadastro.setText("");
				txtEmailCadastro.setText("");
				
			}else{
				JOptionPane.showMessageDialog(rootPane,
						"Falha ao cadastrar!");
			}
		}
		
    }//GEN-LAST:event_btnConfirmarCadastroClienteActionPerformed

    private void btnPesquisarNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeClienteActionPerformed
		String nomePesquisa = txtNomeConsultar.getText().trim();
    
		ArrayList<Cliente> lista;
		if (nomePesquisa.isEmpty()) {
			lista = ClienteDAO.listar();
		} else {
			lista = ClienteDAO.buscarPorNomeParcial(nomePesquisa);
		}

		DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
		modeloTabela.setRowCount(0);

		for (Cliente item : lista) {
			modeloTabela.addRow(new String[]{
				String.valueOf(item.getIdCliente()),
				item.getCPF(),
				item.getNomeCliente(),
				item.getEmailCliente()
			});
		}
    }//GEN-LAST:event_btnPesquisarNomeClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
		
		DefaultTableModel modeloClientes = (DefaultTableModel) tblClientes.getModel();
		
		int linhaSelecionada = tblClientes.getSelectedRow();
		
		if(linhaSelecionada >=0){
		
			int id = Integer.parseInt(modeloClientes.getValueAt(linhaSelecionada, 0).toString());
			String cpf = modeloClientes.getValueAt(linhaSelecionada, 1).toString();
			String nome = modeloClientes.getValueAt(linhaSelecionada,2).toString();
			String email = modeloClientes.getValueAt(linhaSelecionada, 3).toString();
			
			objAlterar = new Cliente(id, nome, email, cpf);
			
			//Redireciono para a tela de cadastro
			pnlGuiasCliente.setSelectedIndex(0);
			
			lblIDCliente.setText(String.valueOf(objAlterar.getIdCliente()));
			txtNomeCadastro.setText(objAlterar.getNomeCliente());
			txtCPFCadastro.setText(objAlterar.getCPF());
			txtEmailCadastro.setText(objAlterar.getEmailCliente());

		}else{
			JOptionPane.showMessageDialog(rootPane, 
					"Selecione uma linha da tabela!");
		}
		
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
		
		int linhaSelecionada = tblClientes.getSelectedRow();
		
		if(linhaSelecionada>=0){
			
			//TODO: Chamar a DAO para excluir
			DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
			int idExcluir = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString());
			
			boolean retorno = ClienteDAO.excluir(idExcluir);
			
			if(retorno){
				JOptionPane.showMessageDialog(rootPane, 
						"Cliente excluído com sucesso");
				
				atualizarTabela();
				
			}else{
				JOptionPane.showMessageDialog(rootPane,
						"Falha na exclusão");
			}		   

			
		}
		
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

        private void txtNomeConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeConsultarActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txtNomeConsultarActionPerformed

	public void atualizarTabela(){
	
		ArrayList<Cliente> lista = ClienteDAO.listar();
		
		DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
		
		modeloTabela.setRowCount(0);
		
		for (Cliente item : lista) {
			
			modeloTabela.addRow(new String[]{
					String.valueOf(item.getIdCliente()),
					item.getCPF(),
					item.getNomeCliente(),
					item.getEmailCliente()
			});
			
		}
		
	}
	
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaClientes(0).setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAlterarCliente;
        private javax.swing.JButton btnCancelarCadastroCliente;
        private javax.swing.JButton btnConfirmarCadastroCliente;
        private javax.swing.JButton btnExcluirCliente;
        private javax.swing.JButton btnPesquisarNomeCliente;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblIDCliente;
        private javax.swing.JPanel pnlCadastroCliente;
        private javax.swing.JPanel pnlConsultarCliente;
        private javax.swing.JTabbedPane pnlGuiasCliente;
        private javax.swing.JTable tblClientes;
        private javax.swing.JFormattedTextField txtCPFCadastro;
        private javax.swing.JTextField txtEmailCadastro;
        private javax.swing.JTextField txtNomeCadastro;
        private javax.swing.JTextField txtNomeConsultar;
        // End of variables declaration//GEN-END:variables
}
