/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.leafcabral.pontoDeVenda.views;

import com.leafcabral.pontoDeVenda.dao.ClienteDAO;
import com.leafcabral.pontoDeVenda.dao.ProdutoDAO;
import com.leafcabral.pontoDeVenda.dao.RelatorioAnaliticoDAO;
import com.leafcabral.pontoDeVenda.dao.RelatorioSinteticoDAO;
import com.leafcabral.pontoDeVenda.dao.VendaDAO;
import com.leafcabral.pontoDeVenda.models.Cliente;
import com.leafcabral.pontoDeVenda.models.ItemVenda;
import com.leafcabral.pontoDeVenda.models.Produto;
import com.leafcabral.pontoDeVenda.models.RelatorioAnalitico;
import com.leafcabral.pontoDeVenda.models.RelatorioSintetico;
import com.leafcabral.pontoDeVenda.models.Venda;
import java.awt.Desktop;
import java.awt.Image;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ftfer
 */
public class TelaPrincipal extends javax.swing.JFrame {

	Venda objVenda = new Venda();
	float valorTotal = 0;
		
	/**
	 * Creates new form TelaPrincipal
	 */
	public TelaPrincipal() {
		LoginDialog login = new LoginDialog(this, true);
		login.setVisible(true);
		if (!login.isLoginSuccessful()) {
			System.exit(0);
			return;
		}
		
		initComponents();
		
		recarregarTabelaVendas();
		pesquisarRelatorio();
		
		this.setLocationRelativeTo(null);
		
		try {
			Image i = ImageIO.read(getClass().getResource("/APP-ICON.png"));
			this.setIconImage(i);
		} catch (Exception e) { e.printStackTrace(); }
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                contentTabbedPane = new javax.swing.JTabbedPane();
                vendasPanel = new javax.swing.JPanel();
                cpfLabel = new javax.swing.JLabel();
                cpfFormattedTextField = new javax.swing.JFormattedTextField();
                cpfBuscarButton = new javax.swing.JButton();
                nomeClienteLabel = new javax.swing.JLabel();
                selecionarProdutosComboBox = new javax.swing.JComboBox<>();
                quantidadeSpinner = new javax.swing.JSpinner();
                adicionarProdutoButton = new javax.swing.JButton();
                produtosScrollPanel = new javax.swing.JScrollPane();
                produtosTable = new javax.swing.JTable();
                excluirButton = new javax.swing.JButton();
                vendaTotalLabel = new javax.swing.JLabel();
                vendaTotalValorLabel = new javax.swing.JLabel();
                confirmarButton = new javax.swing.JButton();
                cancelarButton = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();
                relatoriosPanel = new javax.swing.JPanel();
                detalhesButton = new javax.swing.JButton();
                dataInicioLabel = new javax.swing.JLabel();
                dataInicioValorLabel = new javax.swing.JLabel();
                dataTerminoLabel = new javax.swing.JLabel();
                dataTerminoValorLabel = new javax.swing.JLabel();
                relatoriosScrollPane = new javax.swing.JScrollPane();
                relatoriosSinteticoTable = new javax.swing.JTable();
                valorTotalLabel = new javax.swing.JLabel();
                valorTotalValorLabel = new javax.swing.JLabel();
                procurarButton = new javax.swing.JButton();
                inicioDataChooser = new com.toedter.calendar.JDateChooser();
                fimDataChooser = new com.toedter.calendar.JDateChooser();
                relatoriosScrollPane1 = new javax.swing.JScrollPane();
                detalhesTable = new javax.swing.JTable();
                navbarMenuBar = new javax.swing.JMenuBar();
                arquivoMenu = new javax.swing.JMenu();
                mnuProdutos = new javax.swing.JMenu();
                mnuCadastrarProduto = new javax.swing.JMenuItem();
                mnuConsultarProduto = new javax.swing.JMenuItem();
                mnuClientes = new javax.swing.JMenu();
                mnuCadastrarClientes = new javax.swing.JMenuItem();
                mnuConsultarClientes = new javax.swing.JMenuItem();
                mnuSair = new javax.swing.JMenuItem();
                ajudaMenu = new javax.swing.JMenu();
                visitarCodigoFonteMenuItem = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Ponto de Venda - Leaf's Edition");

                contentTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

                cpfLabel.setText("CPF:");

                try {
                        cpfFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
                } catch (java.text.ParseException ex) {
                        ex.printStackTrace();
                }
                cpfFormattedTextField.setToolTipText("Digite seu CPF no formato xxx.xxx.xxx-xx");
                cpfFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cpfFormattedTextFieldActionPerformed(evt);
                        }
                });

                cpfBuscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-icon.png"))); // NOI18N
                cpfBuscarButton.setText("Buscar");
                cpfBuscarButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBuscarCPFActionPerformed(evt);
                        }
                });

                selecionarProdutosComboBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                selecionarProdutosComboBoxActionPerformed(evt);
                        }
                });

                quantidadeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

                adicionarProdutoButton.setText("Adicionar");
                adicionarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAdicionarActionPerformed(evt);
                        }
                });

                produtosTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "ID Produto", "Codigo", "Nome", "Qtd", "Vlr Unitário"
                        }
                ));
                produtosScrollPanel.setViewportView(produtosTable);

                excluirButton.setForeground(new java.awt.Color(255, 102, 102));
                excluirButton.setText("Excluir");
                excluirButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                excluirButtonActionPerformed(evt);
                        }
                });

                vendaTotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                vendaTotalLabel.setText("Valor Total:");

                confirmarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-icon.png"))); // NOI18N
                confirmarButton.setText("Confirmar");
                confirmarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
                confirmarButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnConfirmarActionPerformed(evt);
                        }
                });

                cancelarButton.setForeground(new java.awt.Color(255, 102, 102));
                cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross-icon.png"))); // NOI18N
                cancelarButton.setText("Cancelar");
                cancelarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
                cancelarButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelarActionPerformed(evt);
                        }
                });

                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rotate-right.png"))); // NOI18N
                jButton1.setText("Recarregar");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout vendasPanelLayout = new javax.swing.GroupLayout(vendasPanel);
                vendasPanel.setLayout(vendasPanelLayout);
                vendasPanelLayout.setHorizontalGroup(
                        vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vendasPanelLayout.createSequentialGroup()
                                .addGroup(vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(vendasPanelLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(vendaTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3)
                                                .addComponent(vendaTotalValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(399, 399, 399)
                                                .addComponent(confirmarButton))
                                        .addGroup(vendasPanelLayout.createSequentialGroup()
                                                .addGap(600, 600, 600)
                                                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(vendasPanelLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addGroup(vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(vendasPanelLayout.createSequentialGroup()
                                                                .addComponent(cpfLabel)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(cpfBuscarButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(nomeClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(vendasPanelLayout.createSequentialGroup()
                                                                        .addComponent(selecionarProdutosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(quantidadeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButton1)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(adicionarProdutoButton)
                                                                        .addGap(6, 6, 6)
                                                                        .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(produtosScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(300, Short.MAX_VALUE))
                );
                vendasPanelLayout.setVerticalGroup(
                        vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vendasPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cpfFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cpfBuscarButton))
                                        .addGroup(vendasPanelLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cpfLabel)
                                                        .addComponent(nomeClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addGroup(vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(selecionarProdutosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(quantidadeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton1))
                                        .addComponent(adicionarProdutoButton)
                                        .addComponent(excluirButton))
                                .addGap(12, 12, 12)
                                .addComponent(produtosScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(vendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vendaTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vendaTotalValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(confirmarButton))
                                .addGap(5, 5, 5)
                                .addComponent(cancelarButton))
                );

                contentTabbedPane.addTab("Vendas", vendasPanel);

                detalhesButton.setText("Detalhes");
                detalhesButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDetalhesActionPerformed(evt);
                        }
                });

                dataInicioLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                dataInicioLabel.setText("Data Inicio:");

                dataTerminoLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                dataTerminoLabel.setText("Data Término:");

                relatoriosSinteticoTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "ID", "Data", "Cliente", "Valor Total"
                        }
                ));
                relatoriosScrollPane.setViewportView(relatoriosSinteticoTable);

                valorTotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                valorTotalLabel.setText("Valor Total:");

                procurarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-icon.png"))); // NOI18N
                procurarButton.setText("Procurar");
                procurarButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPesquisarActionPerformed(evt);
                        }
                });

                detalhesTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null}
                        },
                        new String [] {
                                "Nome", "Qtd", "Vlr Unitário"
                        }
                ));
                relatoriosScrollPane1.setViewportView(detalhesTable);

                javax.swing.GroupLayout relatoriosPanelLayout = new javax.swing.GroupLayout(relatoriosPanel);
                relatoriosPanel.setLayout(relatoriosPanelLayout);
                relatoriosPanelLayout.setHorizontalGroup(
                        relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(relatoriosPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(relatoriosPanelLayout.createSequentialGroup()
                                                .addComponent(valorTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(valorTotalValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(222, 222, 222)
                                                .addComponent(detalhesButton))
                                        .addGroup(relatoriosPanelLayout.createSequentialGroup()
                                                .addGroup(relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, relatoriosPanelLayout.createSequentialGroup()
                                                                .addComponent(dataTerminoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(fimDataChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, relatoriosPanelLayout.createSequentialGroup()
                                                                .addComponent(dataInicioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(inicioDataChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(procurarButton))
                                        .addComponent(relatoriosScrollPane))
                                .addGroup(relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(relatoriosPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dataInicioValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(93, 93, 93)
                                                .addComponent(dataTerminoValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(relatoriosPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(relatoriosScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );
                relatoriosPanelLayout.setVerticalGroup(
                        relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(relatoriosPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(relatoriosPanelLayout.createSequentialGroup()
                                                .addGroup(relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dataTerminoValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dataInicioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dataInicioValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(inicioDataChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(dataTerminoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fimDataChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(procurarButton))
                                .addGap(18, 18, 18)
                                .addGroup(relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(relatoriosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(relatoriosScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(valorTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(detalhesButton))
                                .addGap(40, 40, 40)
                                .addComponent(valorTotalValorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                contentTabbedPane.addTab("Relatórios", relatoriosPanel);

                arquivoMenu.setText("Arquivo");

                mnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/box-open-full-icon.png"))); // NOI18N
                mnuProdutos.setText("Produtos");

                mnuCadastrarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                mnuCadastrarProduto.setText("Cadastrar");
                mnuCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mnuCadastrarProdutoActionPerformed(evt);
                        }
                });
                mnuProdutos.add(mnuCadastrarProduto);

                mnuConsultarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
                mnuConsultarProduto.setText("Consultar");
                mnuConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mnuConsultarProdutoActionPerformed(evt);
                        }
                });
                mnuProdutos.add(mnuConsultarProduto);

                arquivoMenu.add(mnuProdutos);

                mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-icon.png"))); // NOI18N
                mnuClientes.setText("Clientes");

                mnuCadastrarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                mnuCadastrarClientes.setText("Cadastrar");
                mnuCadastrarClientes.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mnuCadastrarClientesActionPerformed(evt);
                        }
                });
                mnuClientes.add(mnuCadastrarClientes);

                mnuConsultarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
                mnuConsultarClientes.setText("Consultar");
                mnuConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mnuConsultarClientesActionPerformed(evt);
                        }
                });
                mnuClientes.add(mnuConsultarClientes);

                arquivoMenu.add(mnuClientes);

                mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
                mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit-icon.png"))); // NOI18N
                mnuSair.setText("Sair");
                mnuSair.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mnuSairActionPerformed(evt);
                        }
                });
                arquivoMenu.add(mnuSair);

                navbarMenuBar.add(arquivoMenu);

                ajudaMenu.setText("Ajuda");

                visitarCodigoFonteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
                visitarCodigoFonteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/github.png"))); // NOI18N
                visitarCodigoFonteMenuItem.setText("Visitar código-fonte");
                visitarCodigoFonteMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                visitarCodigoFonteMenuItemActionPerformed(evt);
                        }
                });
                ajudaMenu.add(visitarCodigoFonteMenuItem);

                navbarMenuBar.add(ajudaMenu);

                setJMenuBar(navbarMenuBar);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(contentTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(contentTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	private void recarregarTabelaVendas() {
		selecionarProdutosComboBox.removeAllItems();

		ArrayList<Produto> listaProdutos =  ProdutoDAO.listar();
		if (listaProdutos != null) {
			for(Produto item : listaProdutos){
				selecionarProdutosComboBox.addItem(item);
			}
		}
	}
	
    private void btnBuscarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCPFActionPerformed
		String cpf = cpfFormattedTextField.getText();
		
		Cliente objRetorno = ClienteDAO.buscarPorCPF(cpf);
		
		if(objRetorno != null){
			nomeClienteLabel.setText(objRetorno.getNomeCliente());
			objVenda.setIdCliente(objRetorno.getIdCliente());
		}
		
    }//GEN-LAST:event_btnBuscarCPFActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
		
		Produto produtoSelecionado = (Produto) selecionarProdutosComboBox.getSelectedItem();
		
		if (produtoSelecionado != null){
			DefaultTableModel modelo = (DefaultTableModel)produtosTable.getModel();
			modelo.addRow(new String[]{
				String.valueOf(produtoSelecionado.getIdProduto()),
				String.valueOf(produtoSelecionado.getCodProduto()),
				produtoSelecionado.getNomeProduto(),
				String.valueOf(Integer.parseInt(quantidadeSpinner.getValue().toString())),
				String.valueOf(produtoSelecionado.getValorProduto())
			});
			
			float valorUnitario = produtoSelecionado.getValorProduto();
			int qtd = Integer.parseInt(quantidadeSpinner.getValue().toString());
			
			float valorLinha = valorUnitario * qtd;
			
			valorTotal += valorLinha;
			
			vendaTotalValorLabel.setText(String.valueOf(valorTotal));
			
		}
		
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
		
		DefaultTableModel modelo = (DefaultTableModel) produtosTable.getModel();
		
		for(int i=0; i< modelo.getRowCount(); i++){
			
			ItemVenda novoItem = null;
			
			int idProduto = Integer.parseInt(modelo.getValueAt(i,0).toString());
			int codProduto = Integer.parseInt(modelo.getValueAt(i,1).toString());
			String nomeProduto = modelo.getValueAt(i,2).toString();
			int qtdProduto = Integer.parseInt(modelo.getValueAt(i,3).toString());
			float vlrUnitario = Float.parseFloat(modelo.getValueAt(i,4).toString());
			
			novoItem = new ItemVenda(idProduto,qtdProduto, vlrUnitario);
			
			objVenda.getListaItens().add(novoItem);
		
		}
		
		objVenda.setValorVenda(Float.parseFloat(vendaTotalValorLabel.getText()));
		objVenda.setDataVenda(new Date());
		
		Cliente objRetorno = ClienteDAO.buscarPorCPF(cpfFormattedTextField.getText());
		
		if(objRetorno != null){
			objVenda.setIdCliente(objRetorno.getIdCliente());
		}
		
		boolean retorno = VendaDAO.salvar(objVenda);
		
		if(retorno){
			JOptionPane.showMessageDialog(rootPane,"Venda realizada com sucesso!");
		}else{
			JOptionPane.showMessageDialog(rootPane,"Falha na venda!");
		}
		
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void mnuCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarProdutoActionPerformed
		TelaProdutos novaTela = new TelaProdutos(0);
		novaTela.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarProdutoActionPerformed

    private void mnuCadastrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarClientesActionPerformed
		TelaClientes novaTela = new TelaClientes(0);
		novaTela.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarClientesActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
		System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

	private void pesquisarRelatorio() {
		Date dataInicio = inicioDataChooser.getDate();
		Date dataTermino = fimDataChooser.getDate();
		
		ArrayList<RelatorioSintetico> lista = RelatorioSinteticoDAO.listarPorPeriodo(dataInicio, dataTermino);
		
		DefaultTableModel modelo = (DefaultTableModel) relatoriosSinteticoTable.getModel();
		modelo.setRowCount(0);
		
		for(RelatorioSintetico item: lista){
		
			modelo.addRow(new String[]{
				String.valueOf(item.getIdVenda()),
				String.valueOf(item.getDataVenda()),
				item.getNomeCliente(),
				String.valueOf(item.getValorVenda())
			});
			
		}
	}
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
		pesquisarRelatorio();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
		
		int linhaSelecionada = relatoriosSinteticoTable.getSelectedRow();
		
		if(linhaSelecionada >= 0 ){
			DefaultTableModel modelo = (DefaultTableModel) relatoriosSinteticoTable.getModel();
			int idVenda = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
			
			//Chamar a DAO do relatório analítico
			ArrayList<RelatorioAnalitico> lista = RelatorioAnaliticoDAO.listarPorVenda(idVenda);
			
			DefaultTableModel modeloAnalitico = (DefaultTableModel) detalhesTable.getModel();
			modeloAnalitico.setRowCount(0);
			
			for (RelatorioAnalitico item : lista) {

				modeloAnalitico.addRow(new String[]{
					item.getNomeProduto(),
					String.valueOf(item.getQtdProduto()),
					String.valueOf(item.getVlrUnitario())
				});
				
			}
		
		}
		
    }//GEN-LAST:event_btnDetalhesActionPerformed

        private void cpfFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFormattedTextFieldActionPerformed
				// TODO add your handling code here:
        }//GEN-LAST:event_cpfFormattedTextFieldActionPerformed

        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
		int resposta = JOptionPane.showConfirmDialog(this, 
			"Cancelar a venda atual?", 
			"Confirmar Cancelamento", 
			JOptionPane.YES_NO_OPTION
		);

		if (resposta == JOptionPane.YES_OPTION) {
			DefaultTableModel modelo = (DefaultTableModel) produtosTable.getModel();
			modelo.setRowCount(0);

			// Reset values
			valorTotal = 0;
			vendaTotalValorLabel.setText("0.0");
			nomeClienteLabel.setText("");
			cpfFormattedTextField.setText("");
			objVenda = new Venda();
			quantidadeSpinner.setValue(1);

			JOptionPane.showMessageDialog(this, "Venda cancelada!");
		}
        }//GEN-LAST:event_btnCancelarActionPerformed

        private void mnuConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarProdutoActionPerformed
 		TelaProdutos novaTela = new TelaProdutos(1);
		novaTela.setVisible(true);
        }//GEN-LAST:event_mnuConsultarProdutoActionPerformed

        private void mnuConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarClientesActionPerformed
		TelaClientes novaTela = new TelaClientes(1);
		novaTela.setVisible(true);
        }//GEN-LAST:event_mnuConsultarClientesActionPerformed

        private void visitarCodigoFonteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitarCodigoFonteMenuItemActionPerformed
		String url = "https://github.com/leafcabral/Ponto-de-Venda";
		Desktop desktop = java.awt.Desktop.getDesktop();
		try {
			desktop.browse(new URI(url));
		} catch (Exception ex) {
			Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
		}
        }//GEN-LAST:event_visitarCodigoFonteMenuItemActionPerformed

        private void selecionarProdutosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarProdutosComboBoxActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_selecionarProdutosComboBoxActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               recarregarTabelaVendas();
        }//GEN-LAST:event_jButton1ActionPerformed

        private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
		int selectedRow = produtosTable.getSelectedRow();
		if (selectedRow >= 0) {
			DefaultTableModel modelo = (DefaultTableModel) produtosTable.getModel();

			// Subtract the value of the removed item from total
			float valorRemovido = Float.parseFloat(modelo.getValueAt(selectedRow, 4).toString()) 
								* Integer.parseInt(modelo.getValueAt(selectedRow, 3).toString());
			valorTotal -= valorRemovido;
			vendaTotalValorLabel.setText(String.valueOf(valorTotal));

			// Remove the row
			modelo.removeRow(selectedRow);

			JOptionPane.showMessageDialog(this, "Item removido com sucesso!", "Excluir", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(this, "Selecione um item para excluir!", "Aviso", JOptionPane.WARNING_MESSAGE);
		}
        }//GEN-LAST:event_excluirButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaPrincipal().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton adicionarProdutoButton;
        private javax.swing.JMenu ajudaMenu;
        private javax.swing.JMenu arquivoMenu;
        private javax.swing.JButton cancelarButton;
        private javax.swing.JButton confirmarButton;
        private javax.swing.JTabbedPane contentTabbedPane;
        private javax.swing.JButton cpfBuscarButton;
        private javax.swing.JFormattedTextField cpfFormattedTextField;
        private javax.swing.JLabel cpfLabel;
        private javax.swing.JLabel dataInicioLabel;
        private javax.swing.JLabel dataInicioValorLabel;
        private javax.swing.JLabel dataTerminoLabel;
        private javax.swing.JLabel dataTerminoValorLabel;
        private javax.swing.JButton detalhesButton;
        private javax.swing.JTable detalhesTable;
        private javax.swing.JButton excluirButton;
        private com.toedter.calendar.JDateChooser fimDataChooser;
        private com.toedter.calendar.JDateChooser inicioDataChooser;
        private javax.swing.JButton jButton1;
        private javax.swing.JMenuItem mnuCadastrarClientes;
        private javax.swing.JMenuItem mnuCadastrarProduto;
        private javax.swing.JMenu mnuClientes;
        private javax.swing.JMenuItem mnuConsultarClientes;
        private javax.swing.JMenuItem mnuConsultarProduto;
        private javax.swing.JMenu mnuProdutos;
        private javax.swing.JMenuItem mnuSair;
        private javax.swing.JMenuBar navbarMenuBar;
        private javax.swing.JLabel nomeClienteLabel;
        private javax.swing.JButton procurarButton;
        private javax.swing.JScrollPane produtosScrollPanel;
        private javax.swing.JTable produtosTable;
        private javax.swing.JSpinner quantidadeSpinner;
        private javax.swing.JPanel relatoriosPanel;
        private javax.swing.JScrollPane relatoriosScrollPane;
        private javax.swing.JScrollPane relatoriosScrollPane1;
        private javax.swing.JTable relatoriosSinteticoTable;
        private javax.swing.JComboBox<Produto> selecionarProdutosComboBox;
        private javax.swing.JLabel valorTotalLabel;
        private javax.swing.JLabel valorTotalValorLabel;
        private javax.swing.JLabel vendaTotalLabel;
        private javax.swing.JLabel vendaTotalValorLabel;
        private javax.swing.JPanel vendasPanel;
        private javax.swing.JMenuItem visitarCodigoFonteMenuItem;
        // End of variables declaration//GEN-END:variables
}
